### ISSUE TITLE
Añade la motivación como primer párrafo de la introducción

### ISSUE THREAD

**Issue by JJ** [lulivi/deep-g-prop#24]
Pero sería cuestión de generalizarla hablando de clasificadores automáticos 
"La clasificación automática es una parte de la IA que pretende... Los clasificadores automáticos son complejos de..."
Más adelante, concretas que lo que se va a tratar en este TFG son los perceptrones multicapa en concreto.

**Comment by lulivi** [comment]
La introducción más general, ¿y especifico lo de los perceptrones en la descripción del problema?

**Comment by JJ** [comment]
@lulivi Si, algo así

**Comment by lulivi** [comment]
@JJ, ¿debería comentar las definiciones de perceptron y perceptron multicapa? Si no, ¿esas definiciones irían en la descripción del problema?

**Comment by JJ** [comment]
@lulivi Si
