### ISSUE TITLE
Integración continua sobre el repo

### ISSUE THREAD

**Issue by JJ** [lulivi/deep-g-prop#3]
- [ ] Tests sobre el código
- [x] Tests de ortografía y demás sobre el informe.

**Comment by lulivi** [comment]
* Probar [pylatexenc](https://github.com/phfaist/pylatexenc) para pasar de `LaTeX` a texto plano y [pyspellchecker](https://pyspellchecker.readthedocs.io/en/latest/index.html) para corrección ortográfica.

**Comment by lulivi** [comment]
Para redes neuronales, ejecutar varias iteraciones y ver que mejora
