### ISSUE TITLE
Decidir qué bibliotecas se van a usar

### ISSUE THREAD

**Issue by JJ** [lulivi/deep-g-prop#4]
Probar diferentes bibliotecas de Python a ver cuál es más potente/flexible

**Comment by lulivi** [comment]
Por ahora se han seleccionado las siguientes librerías:

* [invoke](http://docs.pyinvoke.org/en/1.2/) por su facilidad de uso a la hora de ejecutar procesos (como el de construir la documentación)
* [pytest](https://docs.pytest.org/en/latest/) para ejecutar los tests del software
