### ISSUE TITLE
Automatización del flujo de trabajo

### ISSUE THREAD

**Issue by lulivi** [lulivi/deep-g-prop#6]
Utilizar Invoke para automatizar tareas como la construcción de de la documentación o la ejecución de tests.

**Comment by JJ** [comment]
Como todo lo demás, debes integrar esto dentro de los objetivos generales
del trabajo. Por ejemplo, incluir un objetivo que sea automatizar
fácilmente todos los flujos de trabajo.

**Comment by lulivi** [comment]
¿@JJ podría por ejemplo poner este issue como un check de una lista dentro del issue de automatizar los flujos de trabajo?

**Comment by JJ** [comment]
@lulivi Si
