### ISSUE TITLE
Documenta la metodología de desarrollo que estás siguiendo

### ISSUE THREAD

**Issue by JJ** [lulivi/deep-g-prop#8]
Si est desarrollo basado en test, debes mencionarlo así. En ese sentido, convendría que fueras especificando este tipo de cosas en la memoria mientras las vas haciendo, incluyendo los objetivos del proyecto.

**Comment by lulivi** [comment]
Metodología comentada en b081f3b4a71491eeb012b703277ad97d70e125c7.
